title: CVLEBIKEFEST - Charlottesville Criterium p/b The Dairy Market
email: cvilleracingclub@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Charlottesville Criterium and Bike Fest p/b The Dairy Market
  is April 16 from 10 AM to 4 PM between Downtown Charlottesville and UVA.
baseurl: "/races/charlottesville-criterium" # the subpath of your site, e.g. /blog
url: "https://cvilleracing.com" # the base hostname & protocol for your site, e.g. http://example.com
image: /images/CBF-Insta-Profile.jpg
twitter_username: cvlebikefest
instagram_username: cvlebikefest
facebook_username: CvilleRacingClub

lang: EN_US
permalink: pretty
encoding: "utf-8"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
